name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/'

jobs:
  deploy-lambda: # name of our job
    runs-on: ubuntu-latest # sets or specifies the runner
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python # sets up our python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies # installs any packages
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS Credentials # sets up our AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda Function # zips lambda directory and updates lambda function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
